object Versions {
    const val dagger = "2.44.2"
    const val checkDependencyUpdates = "1.3.0"
    const val stdLib = "1.7.20"
    const val gradle = "7.3.1"
    const val material = "1.3.0"
    const val constraintLayout = "2.1.0"
    const val lifecycle = "2.4.0"
    const val room = "2.5.0"
    const val stetho = "1.6.0"
    const val firebaseCore = "19.0.0"
    const val firebaseAuth = "21.0.1"
    const val firebaseUiAuth = "7.1.1"
    const val desugarJdkLibs = "1.1.5"
    const val detekt = "1.16.0-RC1"
    const val composeBom = "2022.10.00"
    const val themeAdapter = "0.28.0"
    const val glideCompose = "1.0.0-alpha.1"
    const val composeCalendar = "1.0.2"
    const val activityCompose = "1.6.1"
    const val colorPicker = "0.9.0"
}
