name: CI

on:
   pull_request:
    branches:
    - 'master'
env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build_apk:
    if: startsWith(github.head_ref, 'release/') == true
    name: Build release artifact
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
         repository: ${{ secrets.KEYSTORE_REPOSITORY }}
         token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
         path: app/keystore

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Run detekt
        run: ./gradlew detektAll

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
