## This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow pull request events but only for the master branch
  pull_request:
    branches:
    - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build"
  Build:
    name: Run tests and static analyzers on PR in master
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Run detekt
        run: ./gradlew detektAll

      - name: Run ktlint
        run: ./gradlew ktlintCheck
